### ISSUE TITLE
Question: Missing 'coffeescript' and 'stylus' from mimosa-config.coffee?

### ISSUE THREAD

**Issue by jholmberg-cni** [dretay/angularpresentation#1]
Hey @dretay!
This is a cool presentation. It's been a while since I've done web development and this has been really useful to get an understanding of how require, angular, and mimosa all work together.

Quick question, I ran the mimosa watch -s command and got warning statements stating:

WARN - no module has registered for extension: (coffee | styl)

I'm assuming that I just need to add 'coffeescript' and 'stylus' to the modules array in the mimosa-config?

**Comment by dbashford** [comment]
This was prob put together before mimosa 2.0 which yanked all the compilers out of core.  Previously all the compilers were built in.  

Guessing you may have installed the latest mimosa, hence the mismatch.  So yep, that should square you away.

**Comment by jholmberg-cni** [comment]
That did the trick, thanks!
